elixir-nx/bumblebee

lib/bumblebee/diffusion/ddim_scheduler.ex, lib/bumblebee/diffusion/pndm_scheduler.ex
Closes #123.
We used to pass through all args with defaults in defn, but we changed to reserve that behaviour for lists, regardless of default arguments.
=> Pass scheduler to defn via options

lib/bumblebee/text.ex, lib/bumblebee/text/zero_shot_classification.ex, lib/bumblebee/utils/nx.ex, test/bumblebee/text/zero_shot_classification_test.exs
I will add tests tomorrow when I get the multi-prompt case down, but right now it seems to be working fine:
Btw, is there a reason we hid documentation for `TokenClassification` ?
=> Add zero-shot classification

lib/bumblebee/text.ex, lib/bumblebee/text/zero_shot_classification.ex, test/bumblebee/text/zero_shot_classification_test.exs
Similarly to other classification servings we have.
=> Add top-k option to zero-shot classification

lib/bumblebee/audio.ex, lib/bumblebee/audio/speech_to_text.ex
We also wanted support for binary/stream input, but ffmpeg waits for stdin to be closed, which we can't do with ports.
=> Explicitly tag files on speech to text

lib/bumblebee/text.ex, lib/bumblebee/text/question_answering.ex, notebooks/examples.livemd, test/bumblebee/text/question_answering_test.ex
I did some poking around, and I think this is how question answering would be added. I know I need to clean up the docs and some other things like testing but feedback would be appreciated on the overall approach. Thanks so much for the excellent library.
=> Add question answering serving

lib/bumblebee/text.ex, lib/bumblebee/text/conversation.ex, lib/bumblebee/text/gpt2_tokenizer.ex, test/bumblebee/text/conversation_test.exs
=> Add conversational serving

lib/bumblebee/text/generation.ex
Today it's possible to do this:
```elixir
Bumblebee.Text.generation(model, tokenizer,
max_length: 1000,
compile: [batch_size: 1, sequence_length: 1000],
defn_options: [compiler: EXLA]
)
```
However `sequence_length` is used to pad the input, while `max_length` is used as the generation length limit, which means there is no room for generation. Currently we checked `>` rather than `>=`, so it wouldn't be detected.
Sidenote: that's one of the reasons why `max_new_tokens` is preferable over `max_length`.
=> Improve generation sequence length check

lib/bumblebee/text/token_classification.ex, test/bumblebee/text/token_classification_test.exs
Follow up to #174.
For "Janine Doe" we get:
```
Jan   | B-PER
##ine | B-PER
Do    | I-PER
##e   | I-PER
```
When overriding word token labels we need to make sure that non-starting word tokens get the `I-` prefix, so they become a single label during further aggregation.
=> Improve word aggregation with BIO tagging

lib/bumblebee/shared.ex, lib/bumblebee/text/generation.ex, test/bumblebee/text/generation_test.exs
Prevents from n-gram (sequence of n tokens) duplication in generated text.
=> Add :no_repeat_ngram_length option to text generation

lib/bumblebee.ex, lib/bumblebee/huggingface/hub.ex, test/bumblebee/huggingface/hub_test.exs
When deploying an app that points to `{:hf, repo}`, the model can be downloaded as part of the build process. In that case we don't want to make the e-tag validation requests and always read from cache.
=> Add option to load models from cache without outgoing traffic

lib/bumblebee.ex, lib/bumblebee/conversion/pytorch.ex, lib/bumblebee/diffusion/layers/unet.ex, lib/bumblebee/huggingface/transformers/utils.ex
Closes #149.
Currently when all parameters are loaded as expected, we still show unused parameters, and for the end user it's likely more confusing than informative. This changes it, such that we only log if there are any missing/mismatched parameters. The `:log_params_diff` option can still be passed to force either behaviour.
=> Don't log params diff if everything is loaded correctly

lib/bumblebee.ex, lib/bumblebee/layers.ex, lib/bumblebee/vision/blip_vision.ex, lib/bumblebee/vision/clip_vision.ex, lib/bumblebee/vision/deit.ex, lib/bumblebee/vision/vit.ex
We currently have `prepend_embedding` layer for adding embedding for single tokens (like CLS), but I generalized it, such that we just use `embeddings` with whatever shape (could be length-1) and then do `prepend_embedding`.
This was primarily for YOLOS, which I realised relies on dynamic shapes too much, but these changes are useful anyway.
=> Refactor embedding layers

CHANGELOG.md, README.md, examples/phoenix/image_classification.exs, examples/phoenix/speech_to_text.exs, examples/phoenix/text_classification.exs, mix.exs, notebooks/fine_tuning.livemd, notebooks/stable_diffusion.livemd
=> Release v0.3.0

lib/bumblebee.ex, lib/bumblebee/audio/whisper.ex, lib/bumblebee/diffusion/layers/unet.ex, lib/bumblebee/layers.ex, lib/bumblebee/layers/decoder.ex, lib/bumblebee/layers/transformer.ex, lib/bumblebee/text/blenderbot.ex, lib/bumblebee/text/clip_text.ex, lib/bumblebee/text/gpt2.ex, lib/bumblebee/text/gpt_neo_x.ex, lib/bumblebee/text/gpt_neo_x_tokenizer.ex, lib/bumblebee/text/llama.ex, lib/bumblebee/text/mbart.ex, lib/bumblebee/text/t5.ex, lib/bumblebee/utils/axon.ex, lib/bumblebee/vision/blip_vision.ex, lib/bumblebee/vision/clip_vision.ex, lib/bumblebee/vision/deit.ex, lib/bumblebee/vision/vit.ex, test/bumblebee/text/gpt_neo_x_test.exs
Should support StableLM. It's rebased off of Llama for rotary embeddings.
@jonatanklosko I wonder if you might be able to take a look at the sliced qkv calculation? When debugging the values I was getting for `query` are correct, but for `key` they are way off.
=> Add GPT-NeoX (StableLM)

lib/bumblebee/shared.ex, lib/bumblebee/text.ex, lib/bumblebee/text/text_classification.ex, lib/bumblebee/text/token_classification.ex, lib/bumblebee/vision.ex, lib/bumblebee/vision/image_classification.ex
For classification models, users should have some way of specifying the function to be applied to the logits rather than `softmax` always being used since the logits do not always correspond to mutually exclusive classes.
Take, for example, a model's logits representing whether a piece of text conveys negative, neutral, or positive sentiment in a text classification task. In this case, the `softmax` activation function is apt as it ensures that the probabilities in the final output vector sum to 1. However, if the logits denote whether the text is toxic, obscene, insulting, etc. (as seen in [Detoxify models](https://github.com/unitaryai/detoxify)), the `sigmoid` activation function would be more appropriate since the values in the final output vector do not necessarily have to sum to 1. …
=> Add support for `function_to_apply` in classification

lib/bumblebee/text.ex, lib/bumblebee/text/text_embedding.ex, lib/bumblebee/utils/nx.ex, test/bumblebee/text/text_embedding_test.exs
Resolves https://github.com/elixir-nx/bumblebee/issues/206
=> Add text embedding serving

lib/bumblebee.ex, lib/bumblebee/huggingface/hub.ex
See https://github.com/elixir-nx/bumblebee/issues/202.
=> Add Bumblebee.cache_dir/0 for discovering cache location

lib/bumblebee/vision.ex, lib/bumblebee/vision/image_embedding.ex, test/bumblebee/vision/image_embedding_test.exs
- Adds a serving for extracting embeddings from an image using Vision models like clip, blip, vit, deit.
- Supports L2 Normalization of the output embedding via `embedding_processor` attribute, similar to `TextEmbedding`.
=> Add image embedding serving

test/bumblebee/text/bart_test.exs, test/bumblebee/text/blenderbot_test.exs, test/bumblebee/text/generation_test.exs, test/bumblebee/text/mbart_test.exs, test/bumblebee/text/t5_test.exs, test/bumblebee/vision/image_to_text_test.exs
Mostly removing EXLA-compilation from places where EXLA backend is faster for one-off runs.
=> Speed up tests

lib/bumblebee/audio.ex, lib/bumblebee/audio/speech_to_text.ex, lib/bumblebee/diffusion/stable_diffusion.ex, lib/bumblebee/shared.ex, lib/bumblebee/text.ex, lib/bumblebee/text/conversation.ex, lib/bumblebee/text/fill_mask.ex, lib/bumblebee/text/generation.ex, lib/bumblebee/text/question_answering.ex, lib/bumblebee/text/text_classification.ex, lib/bumblebee/text/text_embedding.ex, lib/bumblebee/text/token_classification.ex, lib/bumblebee/text/zero_shot_classification.ex, lib/bumblebee/vision.ex, lib/bumblebee/vision/image_classification.ex, lib/bumblebee/vision/image_embedding.ex, lib/bumblebee/vision/image_to_text.ex
Closes #217.
1. We want to always allocate tokenization input using binary backend, because it's zero copy, and there is no reason to involve XLA too early.
2. A new `:preallocate_params` option that moves params to the device as defined by `:defn_options`. This can be useful with multiple GPUs, where we could load params into CPU and then use `:preallocate_params` so each serving partition allocates params on the corresponding device.
=> Improve tensor allocations in servings

lib/bumblebee/audio.ex, lib/bumblebee/audio/speech_to_text_whisper.ex, lib/bumblebee/text/generation.ex, test/bumblebee/audio/speech_to_text_whisper_test.exs
Large audio is split into multiple chunks, now we support `stream: true`, so that output chunks are emitted as soon as they are available.
=> Add support for streaming speech-to-text results

lib/bumblebee.ex, lib/bumblebee/audio/speech_to_text_whisper.ex, lib/bumblebee/audio/whisper_featurizer.ex, lib/bumblebee/featurizer.ex, lib/bumblebee/text/generation.ex, lib/bumblebee/vision/blip_featurizer.ex, lib/bumblebee/vision/clip_featurizer.ex, lib/bumblebee/vision/convnext_featurizer.ex, lib/bumblebee/vision/deit_featurizer.ex, lib/bumblebee/vision/image_classification.ex, lib/bumblebee/vision/image_embedding.ex, lib/bumblebee/vision/image_to_text.ex, lib/bumblebee/vision/vit_featurizer.ex, test/bumblebee/audio/speech_to_text_whisper_test.exs, test/bumblebee/vision/image_classification_test.exs
=> Move featurizer batch part to serving computation

lib/bumblebee/diffusion/stable_diffusion.ex, lib/bumblebee/text/question_answering.ex, lib/bumblebee/text/text_embedding.ex, lib/bumblebee/text/token_classification.ex, lib/bumblebee/vision/image_embedding.ex
Follow up to #244.
Accessing the whole binary with `Nx.to_flat_list` or `Nx.backend_transfer` is not blocked by ongoing computation, however tensor access involves slicing and therefor does block. So whenever we need to slice, we are going to transfer to binary backend first.
=> Don't block on tensor access in postprocessing

CHANGELOG.md, README.md, mix.exs
=> Release v0.4.0

lib/bumblebee/audio/speech_to_text_whisper.ex, lib/bumblebee/diffusion/stable_diffusion.ex, lib/bumblebee/shared.ex, lib/bumblebee/text/conversation.ex, lib/bumblebee/text/fill_mask.ex, lib/bumblebee/text/generation.ex, lib/bumblebee/text/question_answering.ex, lib/bumblebee/text/text_classification.ex, lib/bumblebee/text/text_embedding.ex, lib/bumblebee/text/token_classification.ex, lib/bumblebee/text/zero_shot_classification.ex, lib/bumblebee/vision/image_classification.ex, lib/bumblebee/vision/image_embedding.ex, lib/bumblebee/vision/image_to_text.ex, test/bumblebee/text/text_embedding_test.exs
*See https://github.com/elixir-nx/xla/issues/58#issuecomment-1808248714.*
When the serving is partitioned and the user passes inputs exceeding the batch size, it we may need to concatenate computation results from multiple devices, which fails. Since we generally transfer to Nx.BinaryBackend in post-processing whenever we need to slice the result, we decided to just transfer it upfront in the serving function, which also solves the concatenate case.
=> Transfer serving computation result to binary backend upfront

lib/bumblebee/multimodal/blip.ex
Makes a difference when running with backend, but none when compiling with EXLA, so it's probably already falling into a graph optimisation.
=> Compute BLIP image embeddings only once during generation

lib/bumblebee/layers.ex
Partially to resolve https://github.com/elixir-nx/axon/issues/544
Llama specifically computes RMS norm in f32 always (this is probably the case with other models). The way to reflect this in an Axon mixed precision policy is to apply the policy with a modifier `except: [:rms_norm]` and it will apply it to all layers by op_name that match that. So we need rms norm here to have an op-name
=> Add op-name to rms norm

lib/bumblebee/text/generation.ex, lib/bumblebee/text/generation/logits_processing.ex, lib/bumblebee/text/generation_config.ex, test/bumblebee/text/generation/logits_processing_test.exs
=> Add temperature to generation options

lib/bumblebee.ex, lib/bumblebee/diffusion/stable_diffusion.ex, notebooks/stable_diffusion.livemd, test/bumblebee/diffusion/stable_diffusion_test.exs, test/bumblebee/diffusion/unet_2d_conditional_test.exs, test/bumblebee/diffusion/vae_kl_test.exs
We now have a listing with all filenames, so we can automatically detect the common files, like `diffusion_pytorch_model.bin` used by hf/diffusers. This simplifies loading for the end user :)
=> Automatically detect diffusers params files

lib/bumblebee/text/conversation.ex, lib/bumblebee/text/generation.ex, test/bumblebee/text/bart_test.exs, test/bumblebee/text/blenderbot_test.exs, test/bumblebee/text/generation_test.exs, test/bumblebee/text/mbart_test.exs, test/bumblebee/text/t5_test.exs
Closes #247.
This changes text generation serving to only return the new text (without the prompt). This is consistent with streaming. Also, encoder-decoder models like BART already don't return the input text, since it is used as a "context" rather than a "prompt" to complete.
This is a small breaking change, but the next release is going to be 0.5.0 and I think it's fine.
Initially I thought about adding an option like `:return_full_text`, but to make it handle leading space in a generic way, we would need to make another tokenizer pass on the input, then prefix replace (that's what hf/transformers do). I don't think this is necessarily worth it, because the end user knows what model they work with, so they can easily concatenate the prompt, either adding a space or not. We can revisit …
=> Return only new text from text generation

lib/bumblebee/audio.ex, lib/bumblebee/audio/speech_to_text_whisper.ex, lib/bumblebee/diffusion/stable_diffusion.ex, lib/bumblebee/text.ex, lib/bumblebee/text/conversation.ex, lib/bumblebee/text/generation.ex, lib/bumblebee/vision.ex, lib/bumblebee/vision/image_to_text.ex, test/bumblebee/text/bart_test.exs, test/bumblebee/text/blenderbot_test.exs, test/bumblebee/text/generation_test.exs, test/bumblebee/text/mbart_test.exs, test/bumblebee/text/t5_test.exs
Closes #284.
Now we can do `Nx.Serving.run(serving, %{text: "...", seed: 0})` for text generation and similar for other servings.
=> Make randomization seed a serving input, rather than compile option

lib/bumblebee/conversion/pytorch.ex, lib/bumblebee/diffusion/unet_2d_conditional.ex, lib/bumblebee/diffusion/vae_kl.ex, lib/bumblebee/huggingface/transformers/model.ex, lib/bumblebee/huggingface/transformers/utils.ex
https://github.com/huggingface/diffusers/pull/3387 changed layer names in the VaeKl implementation, so in order to load newer and older checkpoints we need to check for both layer names. In particular this is relevant to fp16 checkpoints for SDv1-4.
I changed the params mapping to support multiple layer names to try like this:
```elixir
%{
...,
"attentions.{m}.query" => ["attentions.{m}.to_q", "attentions.{m}.query"],
...
}
```
=> Fix loading more recent VaeKl checkpoints

lib/bumblebee.ex, test/bumblebee_test.exs
Small UX improvement:
```diff
-Bumblebee.load_model({:hf, repository_id, subdir: "unet"},
-  params_filename: "diffusion_pytorch_model.fp16.bin"
-)
+Bumblebee.load_model({:hf, repository_id, subdir: "unet"}, params_variant: "fp16")
```
```
iex> Bumblebee.load_model({:hf, repository_id, subdir: "unet"}, params_variant: "f16")
** (ArgumentError) parameters variant "f16" not found, available variants: "fp16", "non_ema"
```
=> Streamline loading for params variants

lib/bumblebee.ex, lib/bumblebee/conversion/pytorch.ex, lib/bumblebee/utils/nx.ex, test/bumblebee_test.exs
Allows for `Bumblebee.load_model({:hf, "..."}, type: :bf16)` to set mixed precision policy on the model and cast params on load. The user can also pass the policy struct itself, type is just a shorthand.
Note: currently loading a f16 checkpoint returns params in f16, but that's somewhat a bug, specifically if all params are available we skip Axon init, which would otherwise cast the params to f32. Now it's going to always be f32 by default and the user can override it using `:type`.
hf/transformers look at `"torch_dtype"` in the config file to determine the type, but I'm not sure if we want to configure the policy automatically based on that. @seanmor5 thoughts?
=> Add :type option to load model under specific precision

notebooks/stable_diffusion.livemd
=> Update Stable Diffusion notebook

lib/bumblebee/audio/speech_to_text_whisper.ex, lib/bumblebee/text/fill_mask.ex, lib/bumblebee/text/text_classification.ex, lib/bumblebee/text/zero_shot_classification.ex, lib/bumblebee/tokenizer.ex, lib/bumblebee/utils/nx.ex, lib/bumblebee/vision/image_classification.ex
After `Nx.to_list/1` (https://github.com/elixir-nx/nx/pull/1095) was added, the function `Bumblebee.Utils.Nx.to_list` became redundant.
=> Remove Bumblebee.Utils.Nx.to_list/1 in favour of Nx.to_list/1

lib/bumblebee.ex, lib/bumblebee/diffusion/ddim_scheduler.ex, lib/bumblebee/diffusion/lcm_scheduler.ex, lib/bumblebee/diffusion/pndm_scheduler.ex, lib/bumblebee/diffusion/stable_diffusion.ex, lib/bumblebee/scheduler.ex, test/bumblebee/diffusion/lcm_scheduler_test.exs
Propagates the per-input seed all the way to the scheduler.
=> Pass PRNG key to schedulers in Stable Diffusion

lib/bumblebee/text/zero_shot_classification.ex
Sometimes labels are in uppercase. So the library raises `(ArgumentError) expected model specification to include "entailment" label in :id_to_label` when building the zero shot classification.
For example here: https://huggingface.co/typeform/distilbert-base-uncased-mnli/blob/main/config.json
I tested this commit and it allows me to use the above mentioned model.
The code I used to test this commit:
```elixir
Nx.default_backend({EXLA.Backend, []})
hf_model = "typeform/distilbert-base-uncased-mnli"
{:ok, model} = Bumblebee.load_model({:hf, hf_model})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "distilbert/distilbert-base-uncased"})
serving = Bumblebee.Text.zero_shot_classification(model, tokenizer, ["Is clothes", "Is food"])
Nx.Serving.run(serving, "Steak is tasty")
```
Thank you …
=> Downcase label before checking equality

lib/bumblebee/shared.ex, lib/bumblebee/shared/converters.ex, lib/bumblebee/vision/blip_featurizer.ex, lib/bumblebee/vision/clip_featurizer.ex, lib/bumblebee/vision/convnext_featurizer.ex, lib/bumblebee/vision/deit_featurizer.ex, lib/bumblebee/vision/vit_featurizer.ex
Initially CLIP was using a single integer as size and always resized the shortest edge. Now it supports both fixed height-width and shortest edge resizing (there is padding on top of it, so the shape is still static).
I updated all featurizers to use maps, such as `%{height: 224, width: 224}` and `%{shortest_edge: 224}`. This matches hf/transformers and in the feature we may need to support more of these (for other featurizers).
=> Change image size to maps in image featurizers

lib/bumblebee/audio/speech_to_text_whisper.ex, lib/bumblebee/text.ex, lib/bumblebee/text/generation.ex, lib/bumblebee/text/pre_trained_tokenizer.ex, lib/bumblebee/text/text_generation.ex, lib/bumblebee/vision/image_to_text.ex, test/bumblebee/text/bart_test.exs, test/bumblebee/text/blenderbot_test.exs, test/bumblebee/text/mbart_test.exs, test/bumblebee/text/t5_test.exs, test/bumblebee/text/text_generation_test.exs
Closes #287.
The summary looks like this `token_summary: %{input: 5, output: 20, padding: 95}`. When streaming, there is a new option `:stream_done`, which enables a final message and includes the usual result except for text, for example `{:done, %{token_summary: ...}}`.
=> Add token summary to text generation output

lib/bumblebee/text/generation.ex, lib/bumblebee/text/text_generation.ex
When streaming tokens, we don't care about the generation final output. This PR changes the result to a zeroed tensor with shape `{batch_size}` (so it can be split by the serving).
=> Reduce the output of generation loop when streaming

lib/bumblebee.ex, test/bumblebee/vision/dino_v2_test.exs
```elixir
{:ok, spec} = Bumblebee.load_spec({:hf, "microsoft/resnet-50"})
spec = Bumblebee.configure(spec, num_labels: 10)
{:ok, resnet} = Bumblebee.load_model({:hf, "microsoft/resnet-50"}, spec: spec)
```
->
```elixir
{:ok, resnet} =
Bumblebee.load_model({:hf, "microsoft/resnet-50"}, spec_overrides: [num_labels: 10])
```
I considered accepting a keyword list for `:spec`, but probably better to kept them separate for clarity.
=> Add :spec_overrides to Bumblebee.load_model/2

lib/bumblebee/text/generation.ex, test/bumblebee/text/bart_test.exs
=> Make sure the initial decoding cache has the proper types

examples/phoenix/README.md, mix.exs, notebooks/llama.livemd, notebooks/llms.livemd, notebooks/stable_diffusion.livemd
I did another iteration of this. Currently running LLaMa 7B with params on the GPU requires 16.3GiB of memory. Params on the CPU + lazy transfers require 15.5GiB, which is almost negligible and given that it adds latency of like x4 inference time, I think it's no longer worth mentioning. Sidenote: lazy transfers don't really change anything here and that's what I would expect, since generation loops over the model and therefor all params need to be on the GPU. I'm sure how not having params on the GPU makes a difference, since they can't be garbage collected early either, but the difference is very tiny anyway.
Note that for Stable Diffusion params on the CPU + lazy transfers has more impact, because it uses several models, so once one finishes its params can be garbage collected and the …
=> Update LLM docs

notebooks/simple_rag.livemd
I built a simple rag pipeline end to end with hnswlib, mistral and gte-small. I used paul graham essay text as my source.
=> Add notebook on RAG

lib/bumblebee/text/gemma.ex
This fix adds `attention_head_size` which is different for Gemma, equal to 256.
Without this, during module building, the runtime would ignore the mismatched shapes and result in unintelligible results.
```
00:15:21.191 [debug] the following parameters were ignored, because of non-matching shape:
* decoder.blocks.24.self_attention.value.kernel (expected {3072, 3072}, got: {3072, 4096})
* decoder.blocks.18.self_attention.value.kernel (expected {3072, 3072}, got: {3072, 4096})
* decoder.blocks.18.self_attention.output.kernel (expected {3072, 3072}, got: {4096, 3072})
...
```
See:
- https://github.com/google-deepmind/gemma/issues/4
=> Add Gemma attention head size

notebooks/examples.livemd
The tokenizer for roberta has been migrated from "roberta-FacebookAI/roberta-base" to "FacebookAI/roberta-base", causing the example to fail.
This commit updates the tokenizer path, thereby fixing the broken example.
=> Update RoBERTa tokenizer in examples

lib/bumblebee/text/pre_trained_tokenizer.ex
Currently, for models that don't specify pad token, we use eos token as the default. However, this breaks if the model repo configures a different eos token, since the pad one is still the default (and may be invalid). This moves the fallback to where we actually use the pad token.
=> Use eos token for padding lazily

notebooks/llms_rag.livemd
The essay in the example livebook has been moved to a new location.
=> Fixed broken link in LLMs and RAG livebook

notebooks/fine_tuning.livemd, notebooks/llms.livemd
Hello!
Fixes two typos in the Livebook examples. I've also ran `aspell` on all `.md` and `.livemd` files to check that there aren't more of those.
=> Fix documentation typos

lib/bumblebee/audio/whisper_featurizer.ex, lib/bumblebee/layers/transformer.ex, lib/bumblebee/shared.ex, lib/bumblebee/tokenizer.ex, lib/bumblebee/vision/blip_featurizer.ex, lib/bumblebee/vision/vit_featurizer.ex
=> Fix typos and improve language

lib/bumblebee.ex, lib/bumblebee/conversion/pytorch_params.ex, mix.lock, test/bumblebee/conversion/pytorch_params_test.exs, test/bumblebee/text/roberta_test.exs, test/bumblebee_test.exs
=> Use model state

lib/bumblebee/text.ex, lib/bumblebee/text/text_embedding.ex, test/bumblebee/text/text_embedding_test.exs
This PR adding support for token pooling for models like [BGE-M3](https://huggingface.co/BAAI/bge-m3). 
```elixir
model_id = "BAAI/bge-m3"
{:ok, model_info} = Bumblebee.load_model({:hf,  model_id})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, model_id})
serving =
Bumblebee.Text.text_embedding(model_info, tokenizer,
output_attribute: :hidden_state,
output_pool: :cls_token_pooling,
embedding_processor: :l2_norm
)
Nx.Serving.run(serving, "A long text to test the embeddings")
%{
embedding: #Nx.Tensor<
f32[1024]
[-0.04741977900266647, -0.02085975557565689, -0.028225498273968697, 0.02299957536160946, -0.011559668928384781, -0.07012897729873657, 0.03340381383895874, -0.01976216770708561, -0.03233117237687111, 0.006122056394815445, -0.010670339688658714, -0.013755269348621368, …
```
=> Add support for CLS token pooling in text embedding

lib/bumblebee/utils/http.ex
The current clauses were never matching.
=> Fix error handling when writing to file during download

lib/bumblebee.ex
A prior commit 8b52612 removed the concept of tokenizer modules and introduced tokenizer types. As part of the change, the sole expected option for the `load_tokenizer` function was changed from `:module` to `:type`.
Unfortunately the commit missed out on changing the error message, which could cause slight confusion amongst devs that use `load_tokenizer` when upgrading bumblebee from pre-v0.5.0.
=> Fix typo in load_tokenizer's ArgumentError

notebooks/llms.livemd
- Add instructions to request access to the model (now required for Mistral)
- Reduce `sequence_length` so notebook is more accessible - I got OOM even though I have a 32Gb RAM laptop
=> Update Mistral LLMs notebook

examples/phoenix/README.md, mix.exs
The only issue I see is that the URLs point to main rather than docs-version branch. @josevalim let me know if you prefer a different approach.
=> Add Phoenix examples readme to docs

notebooks/llms_rag.livemd
Hi, I've noticed that the link to the Mistral documentation was returning a 404, so I am adjusting here to the the new one.
=> Update link to Mistral docs

lib/bumblebee/text/generation.ex
When generating text with `batch_size > 1`, if there are padded batch items, the model gets zeroed input and may output arbitrary tokens. For some models that could be EOS and it would make no difference, but others could keep outputting a random token until the max length is reached (making the generation longer unnecessarily).
=> Fix padded batch items lengthening generation time
