elixir-nx/bumblebee

notebooks/stable_diffusion.livemd

Add the `:stb_image` dependency so the example works.

Fix Livebook example - use Kino.Image instead of stb_image dep

---

lib/bumblebee/text.ex
lib/bumblebee/text/token_classification.ex
test/bumblebee/text/token_classification_test.exs

This doesn't affect anything, just a clarification.

Clarify that token start and end indices refer to bytes

---

lib/bumblebee/diffusion/stable_diffusion.ex
notebooks/stable_diffusion.livemd

Resolves #105 
It looks decent?

Add negative prompts

---

CHANGELOG.md
README.md
examples/phoenix/image_classification.exs
examples/phoenix/text_classification.exs
mix.exs
notebooks/examples.livemd
notebooks/stable_diffusion.livemd

Release v0.1.1

---

test/bumblebee/diffusion/stable_diffusion/safety_checker_test.exs
test/bumblebee/diffusion/stable_diffusion_test.exs
test/bumblebee/diffusion/unet_2d_conditional_test.exs

Add end-to-end test for stable diffusion

---

lib/bumblebee.ex
lib/bumblebee/diffusion/ddim_scheduler.ex
lib/bumblebee/diffusion/layers/unet.ex
lib/bumblebee/diffusion/pndm_scheduler.ex
lib/bumblebee/diffusion/unet_2d_conditional.ex
lib/bumblebee/scheduler.ex
test/support/test_helpers.ex

Support Stable Diffusion v2

---

notebooks/stable_diffusion.livemd

I spent a couple days trying to get my GPU to work with Bumblebee only to find out my particular GPU doesn't have enough VRAM. This warning would have saved me a lot of time.
Signed-off-by: Connor Rigby <connorr@hey.com>

stable diffusion: add warning about system requirements

---

lib/bumblebee/diffusion/stable_diffusion.ex
lib/bumblebee/shared.ex
lib/bumblebee/text/fill_mask.ex
lib/bumblebee/text/generation.ex
lib/bumblebee/text/text_classification.ex
lib/bumblebee/text/token_classification.ex
lib/bumblebee/vision/image_classification.ex
test/bumblebee/text/generation_test.exs

Normalize serving inputs during validation

---

lib/bumblebee/utils/http.ex

Closes #128.
Alternatively we could spawn a separate process to monitor the caller, @josevalim let me know what you prefer :)

Cancel download request when the caller terminates

---

lib/bumblebee.ex
lib/bumblebee/text/xlm_roberta_tokenizer.ex
test/bumblebee/text/xlm_roberta_test.exs
test/bumblebee/text/xlm_roberta_tokenizer_test.exs

Closes #134.
```elixir
{:ok, model_info} = Bumblebee.load_model({:hf, "papluca/xlm-roberta-base-language-detection"})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "papluca/xlm-roberta-base-language-detection"})
serving = Bumblebee.Text.text_classification(model_info, tokenizer)
Nx.Serving.run(serving, "Kraków w śniegu.")
#=> %{
#=>   predictions: [
#=>     %{label: "pl", score: 0.9958330988883972},
#=>     %{label: "el", score: 4.284092574380338e-4},
#=>     %{label: "bg", score: 4.1166096343658864e-4},
#=>     %{label: "es", score: 3.488743386697024e-4},
#=>     %{label: "de", score: 3.1762008438818157e-4}
#=>   ]
#=> }
```

Add XLM-RoBERTa model

---

lib/bumblebee/text.ex
lib/bumblebee/text/token_classification.ex
test/bumblebee/text/token_classification_test.exs

Adds the rest of the missing token classification aggregation strategies

Add max, avg, first token aggregation

---

examples/phoenix/README.md
examples/phoenix/image_classification.exs
examples/phoenix/speech_to_text.exs
examples/phoenix/text_classification.exs

https://user-images.githubusercontent.com/17034772/228926894-265d03bd-c79f-4bf2-b799-f60bf13d0893.mov

Add Whisper Phoenix demo

---

examples/phoenix/README.md

Expand deployment docs

---

lib/bumblebee/utils/image.ex
lib/bumblebee/vision.ex
lib/bumblebee/vision/blip_featurizer.ex
lib/bumblebee/vision/clip_featurizer.ex
lib/bumblebee/vision/convnext_featurizer.ex
lib/bumblebee/vision/deit_featurizer.ex
lib/bumblebee/vision/vit_featurizer.ex
test/bumblebee/vision/convnext_featurizer_test.exs

Normalize image channels in featurizers

---

lib/bumblebee.ex
lib/bumblebee/text/t5.ex
test/bumblebee/text/t5_test.exs

Just the encoder part, example checkpoint [`hkunlp/instructor-large`](https://huggingface.co/hkunlp/instructor-large).

Add T5 encoder model

---

lib/bumblebee/audio/speech_to_text.ex
lib/bumblebee/diffusion/stable_diffusion.ex
lib/bumblebee/shared.ex
lib/bumblebee/text/conversation.ex
lib/bumblebee/text/fill_mask.ex
lib/bumblebee/text/generation.ex
lib/bumblebee/text/question_answering.ex
lib/bumblebee/text/text_classification.ex
lib/bumblebee/text/text_embedding.ex
lib/bumblebee/text/token_classification.ex
lib/bumblebee/text/zero_shot_classification.ex
lib/bumblebee/vision/image_classification.ex
lib/bumblebee/vision/image_to_text.ex

Validate serving compile options

---

lib/bumblebee/shared.ex
lib/bumblebee/text.ex
lib/bumblebee/text/generation.ex
test/bumblebee/text/generation_test.exs

https://github.com/elixir-nx/bumblebee/assets/17034772/2a7fc471-cd48-49d5-bc14-4ff72b405c2e

Add support for streaming text generation result

---

CHANGELOG.md
README.md
mix.exs

Release v0.3.1

---

lib/bumblebee/text/generation.ex
lib/bumblebee/text/generation/logits_processing.ex
test/bumblebee/text/generation/logits_processing_test.exs

Should make the implementations easier to follow :)

Vectorize logits processors and add more tests

---

README.md

Closes #248.
Note that this will benefit from the new error messages after next release :)

Add link to repository inspector

---

notebooks/examples.livemd
notebooks/fine_tuning.livemd
notebooks/llama.livemd
notebooks/stable_diffusion.livemd

Add notebook on Llama 2

---

notebooks/fine_tuning.livemd

Learning rate is an option to the adam optimizer.

Fix fine tuning notebook

---

lib/bumblebee/text.ex
lib/bumblebee/text/clip_text.ex
lib/bumblebee/text/text_embedding.ex
lib/bumblebee/vision.ex
lib/bumblebee/vision/clip_vision.ex
lib/bumblebee/vision/image_embedding.ex
test/bumblebee/text/clip_text_test.exs
test/bumblebee/vision/clip_vision_test.exs

Add projection heads for ClipText and ClipVision

---

lib/bumblebee/layers.ex
lib/bumblebee/layers/transformer.ex
lib/bumblebee/text/llama.ex

Closes #278.
Added `:rotary_embedding_base` to the Llama config, which we already had implemented, and added support for rotary embedding scaling.

Support more rotary embedding options for Llama

---

lib/bumblebee.ex

Load special tokens from tokenizer_config.json

---

lib/bumblebee/huggingface/hub.ex
test/bumblebee/huggingface/hub_test.exs

Closes #313. Also fixes an issue where loading model with auth token fails specifically within HF spaces, where the URL redirects are different and lead directly to an S3 endpoint.

Handle repository redirects and skip authorization header for LFS

---

.github/workflows/test.yaml

Improve slow tests check

---

notebooks/examples.livemd

Updated example to work again.

Using image.file_ref

---

lib/bumblebee/diffusion/pndm_scheduler.ex
test/bumblebee/diffusion/ddim_scheduler_test.exs
test/bumblebee/diffusion/lcm_scheduler_test.exs
test/bumblebee/diffusion/pndm_scheduler_test.exs
test/support/test_helpers.ex

Add scheduler loop tests

---

lib/bumblebee/diffusion/stable_diffusion.ex
test/bumblebee/diffusion/stable_diffusion_test.exs

Merge safety checker batch phase with safety checker computation

---

lib/bumblebee/diffusion/layers.ex
lib/bumblebee/huggingface/transformers/model.ex
lib/bumblebee/layers.ex
test/bumblebee/audio/whisper_test.exs

Fix typos and improve language

---

lib/bumblebee/layers.ex
lib/bumblebee/text/llama.ex
test/bumblebee/text/llama_test.exs

Support Llama 3

---

lib/bumblebee/application.ex
lib/bumblebee/utils/http.ex
mix.exs
mix.lock

Closes #389.
Also, changes CA certs to use `:public_key.cacerts_get()`.

Support http proxies

---

examples/phoenix/image_classification.exs
examples/phoenix/speech_to_text.exs
examples/phoenix/text_classification.exs

Also adds `:cache` to the examples. Closes #396.
cc @wojtekmach :D

Rewrite phoenix examples with phoenix_playground
